In [27]:
#1. Import the NUMPY package under the name np.
import numpy as np

#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
a = np.random.random((2,3,5))
a2 = np.random.rand(2,3,5)


#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
b = np.ones((5,2,3))
b2 = np.full((5,2,3), 1)


#6. Print b.
print(b)


#7. Do a and b have the same size? How do you prove that in Python code?
def array_size_comparision(a,b):
    return a.size == b.size

"""def array_size_comparision(a,b):
    if a.size == b.size:
        return True
    else:
        return False"""
    
array_size_comparision(a,b)



#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
c = np.transpose(b,(1,2,0))


#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d = np.add(a,c)
print(d)
#same size and same shape means all individual element can be added from both array because it exists on both side.


#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
#d is a with 1 added at each value



#12. Multiply a and c. Assign the result to e.
e = np.multiply(a,c)


#13. Does e equal to a? Why or why not?
#e is equal to a because multiplying by one each element does not change them.



#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f = np.empty([2, 3,5])



[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
[[[1.02060992 1.32219887 1.40155395 1.55191925 1.82122086]
  [1.97311417 1.59267085 1.02206563 1.64009815 1.47764766]
  [1.84413814 1.43932477 1.90876996 1.16706411 1.49701302]]

 [[1.91966323 1.7544444  1.61686965 1.88355772 1.65006504]
  [1.604885   1.56951089 1.69700432 1.0547897  1.67727775]
  [1.98139566 1.27082933 1.67811101 1.09387659 1.19623235]]]


In [28]:

f[d == d_min] = 0
f[(d > d_min) & (d < d_mean)] = 25
f[d == d_mean] = 50
f[(d > d_mean) & (d < d_max)] = 75
f[d == d_max] = 100

In [29]:
print(f)

[[[  0.  25.  25.  75.  75.]
  [ 75.  75.  25.  75.  25.]
  [ 75.  25.  75.  25.  25.]]

 [[ 75.  75.  75.  75.  75.]
  [ 75.  75.  75.  25.  75.]
  [100.  25.  75.  25.  25.]]]


In [31]:
f = f.astype(str)

f[f == '0.0'] = 'A'
f[f == '25.0'] = 'B'
#f[f == 50] = 'C'
#f[f == 75] = 'D'
#f[f == 100] = 'E'



In [32]:
f

array([[['A', 'B', 'B', '75.0', '75.0'],
        ['75.0', '75.0', 'B', '75.0', 'B'],
        ['75.0', 'B', '75.0', 'B', 'B']],

       [['75.0', '75.0', '75.0', '75.0', '75.0'],
        ['75.0', '75.0', '75.0', 'B', '75.0'],
        ['100.0', 'B', '75.0', 'B', 'B']]], dtype='<U32')