In [1]:
#1. Import the NUMPY package under the name np.
import numpy as np

#2. Print the NUMPY version and the configuration.
print(np.version.version)

1.16.2


In [2]:
a = np.random.random((2,3,5))
print(a)

[[[0.08793948 0.42832443 0.39430353 0.64280499 0.51325013]
  [0.82622845 0.3892747  0.84819399 0.88340741 0.87358405]
  [0.15383724 0.68725344 0.64906201 0.3419607  0.7010036 ]]

 [[0.05308887 0.12880717 0.1318471  0.07641896 0.35313586]
  [0.76964064 0.24121776 0.62639171 0.23211994 0.96274904]
  [0.4713482  0.40197744 0.24815599 0.4968684  0.92057971]]]


In [9]:
b=np.ones((5,2,3))

In [12]:
def array_size_comparision(a,b):
    if a.size == b.size:
        return True
    else:
        return False
    
array_size_comparision(a,b)

True

In [18]:
c=np.transpose(b,(1,2,0))
print(c.shape)

(2, 3, 5)


In [19]:
print(np.add(a,c))

[[[1.08793948 1.42832443 1.39430353 1.64280499 1.51325013]
  [1.82622845 1.3892747  1.84819399 1.88340741 1.87358405]
  [1.15383724 1.68725344 1.64906201 1.3419607  1.7010036 ]]

 [[1.05308887 1.12880717 1.1318471  1.07641896 1.35313586]
  [1.76964064 1.24121776 1.62639171 1.23211994 1.96274904]
  [1.4713482  1.40197744 1.24815599 1.4968684  1.92057971]]]


In [23]:
d = np.add(a,c)

In [21]:
np.multiply(a,c)

array([[[0.08793948, 0.42832443, 0.39430353, 0.64280499, 0.51325013],
        [0.82622845, 0.3892747 , 0.84819399, 0.88340741, 0.87358405],
        [0.15383724, 0.68725344, 0.64906201, 0.3419607 , 0.7010036 ]],

       [[0.05308887, 0.12880717, 0.1318471 , 0.07641896, 0.35313586],
        [0.76964064, 0.24121776, 0.62639171, 0.23211994, 0.96274904],
        [0.4713482 , 0.40197744, 0.24815599, 0.4968684 , 0.92057971]]])

In [24]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

In [25]:
d_max

1.9627490390741824

In [26]:
d_min

1.0530888706537964

In [27]:
d_mean

1.4844924983148293

In [50]:
f=np.empty([2, 3,5]) 

In [54]:
print(d)

[[[1.08793948 1.42832443 1.39430353 1.64280499 1.51325013]
  [1.82622845 1.3892747  1.84819399 1.88340741 1.87358405]
  [1.15383724 1.68725344 1.64906201 1.3419607  1.7010036 ]]

 [[1.05308887 1.12880717 1.1318471  1.07641896 1.35313586]
  [1.76964064 1.24121776 1.62639171 1.23211994 1.96274904]
  [1.4713482  1.40197744 1.24815599 1.4968684  1.92057971]]]


In [53]:
for i in range(2):
    for j in range(3):
        for k in range(5):
    
            if d[i,j,k]>d_min and d[i,j,k]<d_mean:
                f[i,j,k]=25
            elif d[i,j,k]>d_mean and d[i,j,k]<d_max:
                f[i,j,k]=75
            elif d[i,j,k]==d_mean:
                f[i,j,k]=50
            elif d[i,j,k]==d_min:
                f[i,j,k]=0
            elif d[i,j,k]==d_max:
                f[i,j,k]=100
        
print(f)

[[[ 25.  25.  25.  75.  75.]
  [ 75.  25.  75.  75.  75.]
  [ 25.  75.  75.  25.  75.]]

 [[  0.  25.  25.  25.  25.]
  [ 75.  25.  75.  25. 100.]
  [ 25.  25.  25.  75.  75.]]]


In [58]:
for i in range(2):
    for j in range(3):
        for k in range(5):
    
            if d[i,j,k]>d_min and d[i,j,k]<d_mean:
                x[i,j,k]="B"
            elif d[i,j,k]>d_mean and d[i,j,k]<d_max:
                x[i,j,k]="D"
            elif d[i,j,k]==d_mean:
                x[i,j,k]="C"
            elif d[i,j,k]==d_min:
                x[i,j,k]="A"
            elif d[i,j,k]==d_max:
                x[i,j,k]="E"
        
print(x)

[[['B' 'B' 'B' 'D' 'D']
  ['D' 'B' 'D' 'D' 'D']
  ['B' 'D' 'D' 'B' 'D']]

 [['A' 'B' 'B' 'B' 'B']
  ['D' 'B' 'D' 'B' 'E']
  ['B' 'B' 'B' 'D' 'D']]]


In [57]:
x = x.astype(str)

In [59]:
f = f.astype(str)
for i in range(2):
    for j in range(3):
        for k in range(5):
    
            if d[i,j,k]>d_min and d[i,j,k]<d_mean:
                f[i,j,k]="B"
            elif d[i,j,k]>d_mean and d[i,j,k]<d_max:
                f[i,j,k]="D"
            elif d[i,j,k]==d_mean:
                f[i,j,k]="C"
            elif d[i,j,k]==d_min:
                f[i,j,k]="A"
            elif d[i,j,k]==d_max:
                f[i,j,k]="E"
        
print(f)

[[['B' 'B' 'B' 'D' 'D']
  ['D' 'B' 'D' 'D' 'D']
  ['B' 'D' 'D' 'B' 'D']]

 [['A' 'B' 'B' 'B' 'B']
  ['D' 'B' 'D' 'B' 'E']
  ['B' 'B' 'B' 'D' 'D']]]
